package by.it.academy.controller;

public enum CommandName {
    UNKNOWN_COMMAND, GO_TO_REGISTRATION_PAGE, GO_TO_MAIN_PAGE, GO_TO_AUTHORIZATION_PAGE,
    GO_TO_NEWS_PAGE, LOG_IN, LOG_OUT, GO_TO_ABOUT_PAGE, GO_TO_USER_PAGE, GO_TO_ADMIN_PAGE
    , ADD_NEWS, GO_TO_OFFER_NEWS_PAGE, DELETE_NEWS, PUBLISHED_NEWS, UPDATE_NEWS, GO_TO_UPDATE_NEWS, DELETE_USER, UPDATE_USER_PROFILE, REGISTER_NEW_USER, GO_TO_COMMENTS_PAGE, PUBLISH_COMMENT, DELETE_COMMENT, GO_TO_NEWS_FROM_ID
}
